/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nguyenduyhieu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author ddom6
 */
public class Bai2 extends javax.swing.JFrame {

    private JPanel mainPanel;
    private BoxLayout boxLayout;
    private boolean axis = true;

    private void createJFrame() {
        // create JFrame
        setDefaultCloseOperation(Bai2.EXIT_ON_CLOSE);
        setSize(400, 200);
        // add content
        mainPanel = createMainPanel();
        add(mainPanel);
        // display
        setLocationRelativeTo(null);
        setVisible(true);
    }

    private JPanel createMainPanel() {
        // create panel with BoxLayout
        JPanel panel = new JPanel();
        boxLayout = new BoxLayout(panel, BoxLayout.X_AXIS);
        panel.setLayout(boxLayout);
        // add button change to main panel
        JButton btnChange = new JButton("Boxlayout");
        btnChange.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                change();
            }
        });
        panel.add(btnChange);
        // add list button to main panel
        panel.add(new JButton("X_AXIS"));
        panel.add(new JButton("Y_AXIS"));

        return panel;
    }

    // change axis when click button change
    private void change() {

        int ax = axis ? BoxLayout.Y_AXIS : BoxLayout.X_AXIS;
        // reset boxLayout
        boxLayout = new BoxLayout(mainPanel, ax);
        // set boxLayout to mainPanel
        boxLayout.layoutContainer(mainPanel);
        axis = !axis;
    }

    /**
     * Creates new form Bai2
     */
    public Bai2() {
        initComponents();
        createJFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Học BoxLayout");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
