/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import Entity.DienObject;
import Entity.HGDObject;
import Entity.HopdongObject;
import Entity.NuocObject;
import Entity.ThanhvienObject;
import NguoidungUse.DienUse;
import NguoidungUse.NuocUse;
import NguoidungUse.Thanhviensevice;
import NguoidungUse.hopdongUse;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class GDHGD extends javax.swing.JPanel {

    DefaultTableModel defaultTableModel;
    Thanhviensevice thanhviensevice;
    DienUse dien = new DienUse();
    DienObject dienOB;
    NuocUse nc = new NuocUse();
    NuocObject ncOB;
    private JPanel child;
    String mahogd = "";

    /**
     * Creates new form GDHGD01
     */
    public GDHGD(String mahgd) throws ParseException {
        mahogd = mahgd;
        thanhviensevice = new Thanhviensevice();
        hopdongUse hduse = new hopdongUse();
        dienOB = dien.getOnebyMahgd(mahgd);
        ncOB = nc.getOnebyMahgd(mahgd);
        initComponents();
        lbTiltle.setText(mahgd);
        HopdongObject hd = hduse.getOnebymaHGD(mahgd);
        Date date = new Date();
        String time = hd.getThoihan();
        String text = "";
        DateFormat dateFM = new SimpleDateFormat("yyyy-MM-dd");
        if (dateFM.parse(time).compareTo(date) <= 0) {
            text = mahgd + " cần gia hạn hợp đồng";
            lbif.setText(text);
        }
        if (dienOB.getTrangthai().equals("Chưa đóng")) {
            if (text != "") {
                text += ", thanh toán HĐ điện";
                lbif.setText(text);
            } else {
                text = mahgd + " cần thanh toán HĐ điện";
                lbif.setText(text);
            }
        }
        if (ncOB.getTrangthai().equals("Chưa đóng")) {
            if (text != "") {
                text += ", thanh toán HĐ nước";
                lbif.setText(text);
            } else {
                text = mahgd + " cần thanh toán HĐ nước";
                lbif.setText(text);
            }
        }

        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        defaultTableModel.addColumn("MÃ THÀNH VIÊN");
        defaultTableModel.addColumn("TÊN THÀNH VIÊN");
        defaultTableModel.addColumn("SỐ ĐIỆN THOẠI");
        defaultTableModel.addColumn("NGÀY SINH");
        defaultTableModel.addColumn("MÃ HỘ GIA ĐÌNH");
        defaultTableModel.addColumn("SỐ CMND");
        defaultTableModel.addColumn("EMAIL");
        defaultTableModel.addColumn("GIỚI TÍNH");

        TBHGD01.setModel(defaultTableModel);
        setDATA(thanhviensevice.getOnebyMHGD(mahgd));

    }

    public void setDATA(List<ThanhvienObject> list) {
        for (ThanhvienObject tv : list) {
            defaultTableModel.addRow(new Object[]{tv.getMatv(), tv.getTentv(), tv.getSdt(), tv.getNgaysinh(), tv.getMahgd(), tv.getSdt(), tv.getEmail(), tv.getGioitinh()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_main = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnQLhopdong = new javax.swing.JButton();
        btnQLhoadonNuoc = new javax.swing.JButton();
        btnQLTV = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBHGD01 = new javax.swing.JTable();
        lbif = new javax.swing.JLabel();
        btnQLhoadonDien = new javax.swing.JButton();
        lbTiltle = new javax.swing.JLabel();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        Panel_main.setBackground(new java.awt.Color(204, 255, 255));
        Panel_main.setLayout(new javax.swing.BoxLayout(Panel_main, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        btnQLhopdong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/contract.png"))); // NOI18N
        btnQLhopdong.setText("QL Hợp đồng");
        btnQLhopdong.setPreferredSize(new java.awt.Dimension(150, 33));
        btnQLhopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLhopdongActionPerformed(evt);
            }
        });

        btnQLhoadonNuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bill.png"))); // NOI18N
        btnQLhoadonNuoc.setText("QL Hóa đơn Nước");
        btnQLhoadonNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLhoadonNuocActionPerformed(evt);
            }
        });

        btnQLTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/team.png"))); // NOI18N
        btnQLTV.setText("QL Thành viên");
        btnQLTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTVActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Button-Close-icon-16.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText(" THÔNG TIN VỀ ");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách thành viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 51, 255))); // NOI18N

        TBHGD01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBHGD01);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lbif.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbif.setForeground(new java.awt.Color(250, 0, 0));

        btnQLhoadonDien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/electricity-bill.png"))); // NOI18N
        btnQLhoadonDien.setText("QL Hóa đơn Điện");
        btnQLhoadonDien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLhoadonDienActionPerformed(evt);
            }
        });

        lbTiltle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTiltle.setForeground(new java.awt.Color(250, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lbif, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnQLhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(btnQLhoadonDien)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnQLhoadonNuoc)
                                        .addGap(30, 30, 30)
                                        .addComponent(btnQLTV)))
                                .addGap(30, 30, 30)
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(lbTiltle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTiltle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQLhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLTV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLhoadonDien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLhoadonNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(lbif, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        Panel_main.add(jPanel3);

        add(Panel_main);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLhoadonNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLhoadonNuocActionPerformed
        // TODO add your handling code here:
        child = new GDHDNuoc(mahogd);
        Panel_main.removeAll();
        Panel_main.add(child);
        Panel_main.validate();
    }//GEN-LAST:event_btnQLhoadonNuocActionPerformed

    private void btnQLhopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLhopdongActionPerformed
        // TODO add your handling code here:
        child = new GDHopdong(mahogd);
        Panel_main.removeAll();
        Panel_main.add(child);
        Panel_main.validate();

    }//GEN-LAST:event_btnQLhopdongActionPerformed

    private void btnQLhoadonDienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLhoadonDienActionPerformed
        // TODO add your handling code here:
        child = new GDHDDien(mahogd);
        Panel_main.removeAll();
        Panel_main.add(child);
        Panel_main.validate();
    }//GEN-LAST:event_btnQLhoadonDienActionPerformed

    private void btnQLTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTVActionPerformed
        // TODO add your handling code here:
        child = new GDQLThanhvien(mahogd);
        Panel_main.removeAll();
        Panel_main.add(child);
        Panel_main.validate();
    }//GEN-LAST:event_btnQLTVActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int comfirm = JOptionPane.showConfirmDialog(this, "BẠN CÓ CHẮC CHẮN MUỐN THOÁT KHÔNG ?");
        if (comfirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            int comfirm = JOptionPane.showConfirmDialog(this, "BẠN CÓ CHẮC CHẮN MUỐN THOÁT KHÔNG ?");
            if (comfirm == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_formKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_main;
    private javax.swing.JTable TBHGD01;
    private javax.swing.JButton btnQLTV;
    private javax.swing.JButton btnQLhoadonDien;
    private javax.swing.JButton btnQLhoadonNuoc;
    private javax.swing.JButton btnQLhopdong;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTiltle;
    private javax.swing.JLabel lbif;
    // End of variables declaration//GEN-END:variables
}
