/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import Entity.ThanhvienObject;
import NguoidungUse.Thanhviensevice;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class GDQLThanhvien extends javax.swing.JPanel {
    DefaultTableModel defaultTableModel;
    Thanhviensevice thanhviensevice;
    /**
     * Creates new form GGQLThanhvien
     */
    public GDQLThanhvien() {
        thanhviensevice = new Thanhviensevice();
        initComponents();
        btnThem.setEnabled(false);
        LoadMTV();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
        defaultTableModel.addColumn("MÃ THÀNH VIÊN");
        defaultTableModel.addColumn("TÊN THÀNH VIÊN");
        defaultTableModel.addColumn("MÃ HỘ GIA ĐÌNH");
        defaultTableModel.addColumn("SỐ ĐIỆN THOẠI");
        defaultTableModel.addColumn("NGÀY SINH");
        defaultTableModel.addColumn("SỐ CMND");
        defaultTableModel.addColumn("EMAIL");
        defaultTableModel.addColumn("GIỚI TÍNH");
         
        TBThanhvien.setModel(defaultTableModel);
        setDATA(thanhviensevice.getALL());
    }
    public GDQLThanhvien(String mahgd) {
        thanhviensevice = new Thanhviensevice();
        initComponents();
        btnThem.setEnabled(false);
        LoadMTV();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
        defaultTableModel.addColumn("MÃ THÀNH VIÊN");
        defaultTableModel.addColumn("TÊN THÀNH VIÊN");
        defaultTableModel.addColumn("MÃ HỘ GIA ĐÌNH");
        defaultTableModel.addColumn("SỐ ĐIỆN THOẠI");
        defaultTableModel.addColumn("NGÀY SINH");
        defaultTableModel.addColumn("SỐ CMND");
        defaultTableModel.addColumn("EMAIL");
        defaultTableModel.addColumn("GIỚI TÍNH");
         
        TBThanhvien.setModel(defaultTableModel);
        setDATA(thanhviensevice.getOnebyMHGD(mahgd));
    }
    public void LoadMTV()
    {
        Thanhviensevice thanhviensevice = new Thanhviensevice();
        List<ThanhvienObject> tv = thanhviensevice.getALL();
        MATVCB.removeAll();;
        for (ThanhvienObject object : tv) {
            MATVCB.addItem(object.getMatv());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TVTBALE = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MATVTF = new javax.swing.JTextField();
        HOTENTF = new javax.swing.JTextField();
        SDTTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MAHGDTF = new javax.swing.JTextField();
        SOCMNDTF = new javax.swing.JTextField();
        EMAILTF = new javax.swing.JTextField();
        NAMCHECK = new javax.swing.JRadioButton();
        NUCHECK = new javax.swing.JRadioButton();
        DatePIcker = new org.jdesktop.swingx.JXDatePicker();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBThanhvien = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        MATVCB = new javax.swing.JComboBox<>();
        btnTimkiem = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnDong = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        jScrollPane1.setBorder(null);

        TVTBALE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TVTBALE);

        setBackground(new java.awt.Color(204, 255, 255));
        setMaximumSize(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÝ THÀNH VIÊN");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanel2.setToolTipText("");

        jLabel2.setText("Mã thành viên");

        jLabel3.setText("Họ tên");

        jLabel4.setText("Số điện thoại");

        jLabel5.setText("Ngày sinh");

        MATVTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MATVTFKeyPressed(evt);
            }
        });

        jLabel6.setText("Mã hộ gia đình");

        jLabel7.setText("Số CMND");

        jLabel8.setText("Email");

        jLabel9.setText("Giới tính");

        NAMCHECK.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(NAMCHECK);
        NAMCHECK.setSelected(true);
        NAMCHECK.setText("Nam");

        NUCHECK.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(NUCHECK);
        NUCHECK.setText(" Nữ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MATVTF)
                    .addComponent(HOTENTF)
                    .addComponent(SDTTF)
                    .addComponent(DatePIcker, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(NAMCHECK)
                        .addGap(18, 18, 18)
                        .addComponent(NUCHECK)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EMAILTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SOCMNDTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MAHGDTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(MATVTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HOTENTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(MAHGDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SOCMNDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EMAILTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NAMCHECK)
                            .addComponent(NUCHECK)
                            .addComponent(jLabel5)
                            .addComponent(DatePIcker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel4)
                    .addComponent(SDTTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách thành viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 51, 255))); // NOI18N

        TBThanhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBThanhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBThanhvienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TBThanhvien);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/search-icon-24.png"))); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        jLabel10.setText("Mã thành viên");

        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Button-Close-icon-16.png"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/reuse.png"))); // NOI18N
        btnOK.setText("Làm mới");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btnThem)
                .addGap(28, 28, 28)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MATVCB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnTimkiem)
                .addGap(23, 23, 23)
                .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MATVCB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 185, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(431, 431, 431))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void setDATA(List<ThanhvienObject> list)
    {
        for (ThanhvienObject tv : list) {
             defaultTableModel.addRow(new Object[]
             {tv.getMatv(),tv.getTentv(),tv.getMahgd()
             ,tv.getSdt(),tv.getNgaysinh(),tv.getSocmnd(),
              tv.getEmail(),tv.getGioitinh()});
        }
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = TVTBALE.getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(this, "VUI LÒNG CHỌN DÒNG CẦN XÓA ","LỖI",JOptionPane.ERROR_MESSAGE);
        }
        else{
            int comfirm = JOptionPane.showConfirmDialog(this, "BẠN CÓ CHẮC CHẮN KHÔNG ?");
            if(comfirm == JOptionPane.YES_OPTION)
            {
                String matv = String.valueOf(TVTBALE.getValueAt(row, 0));
                thanhviensevice.XoaTV(matv);
                defaultTableModel.setRowCount(0);
                setDATA(thanhviensevice.getALL());
                ClearText();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        ThanhvienObject tv = new ThanhvienObject();
        tv.setMatv(MATVTF.getText());
        tv.setTentv(HOTENTF.getText());
        tv.setSdt(SDTTF.getText());
        tv.setMahgd(MAHGDTF.getText());
        tv.setSocmnd(SOCMNDTF.getText());
        String gioitinh ="";
        if(NAMCHECK.isSelected())
            gioitinh = "NAM";
        if(NUCHECK.isSelected())
            gioitinh = "NỮ";
        tv.setGioitinh(gioitinh);
        tv.setEmail(EMAILTF.getText());
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(DatePIcker.getDate());
        tv.setNgaysinh(String.valueOf(date));
        
        if(thanhviensevice.CheckADD(MATVTF.getText()) == 1)
        {
            JOptionPane.showMessageDialog(this, "Mã thành viên '"+MATVTF.getText()+"' đã tồn tại","Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Thêm thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
            thanhviensevice.themTV(tv);
            defaultTableModel.setRowCount(0);
            setDATA(thanhviensevice.getALL());
            ClearText();
        }
    }//GEN-LAST:event_btnThemActionPerformed
    void ClearText()
    {
        MATVTF.setText("");
        HOTENTF.setText("");
        SDTTF.setText("");
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            DatePIcker.setDate(dateFormat.parse("2021-1-1"));
        } catch (ParseException ex) {
            Logger.getLogger(GDQLThanhvien.class.getName()).log(Level.SEVERE, null, ex);
        }
        MAHGDTF.setText("");
        SOCMNDTF.setText("");
        EMAILTF.setText("");
     
        NAMCHECK.setSelected(true);
    }
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        ClearText();
        btnOK.setEnabled(true);
        btnThem.setEnabled(true);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        int comfirm = JOptionPane.showConfirmDialog(this, "BẠN CÓ CHẮC CHẮN MUỐN THOÁT KHÔNG ?");
        if(comfirm == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        ThanhvienObject tv = new ThanhvienObject();
        tv.setMatv(MATVTF.getText());
        tv.setTentv(HOTENTF.getText());
        tv.setSdt(SDTTF.getText());
        tv.setMahgd(MAHGDTF.getText());
        tv.setSocmnd(SOCMNDTF.getText());
        String gioitinh ="";
        if(NAMCHECK.isSelected())
            gioitinh = "NAM";
        if(NUCHECK.isSelected())
            gioitinh = "NỮ";
        tv.setGioitinh(gioitinh);
        tv.setEmail(EMAILTF.getText());
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(DatePIcker.getDate());
        tv.setNgaysinh(String.valueOf(date));
        
        thanhviensevice.updateTV(tv);
        defaultTableModel.setRowCount(0);
        setDATA(thanhviensevice.getALL());
        ClearText();
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
        String matv = String.valueOf(MATVCB.getSelectedItem());
        ThanhvienObject tv = thanhviensevice.getOneByID(matv);
        if(tv == null)
        {
            JOptionPane.showMessageDialog(this, "Không có thành viên trên ","LỖI ",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            defaultTableModel.setRowCount(0);
            defaultTableModel.addRow(new Object[]{tv.getMatv(),tv.getTentv(),tv.getSdt(),tv.getNgaysinh(),tv.getMahgd(),tv.getSdt(),tv.getEmail(),tv.getGioitinh()});
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void MATVTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MATVTFKeyPressed
        // TODO add your handling code here:
        if(MATVTF.getText().equals(""))
        {
            btnThem.setEnabled(false);
        }
        else btnThem.setEnabled(true);
    }//GEN-LAST:event_MATVTFKeyPressed

    private void TBThanhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBThanhvienMouseClicked
        // TODO add your handling code here:
        int row = TBThanhvien.getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(this, "VUI LÒNG CHỌN DÒNG","LỖI",JOptionPane.ERROR_MESSAGE);
        }
        else{
            String matv = String.valueOf(TBThanhvien.getValueAt(row, 0));
            ThanhvienObject tv = thanhviensevice.getOne(matv);
            MATVTF.setText(tv.getMatv());
            HOTENTF.setText(tv.getTentv());
            SDTTF.setText(tv.getSdt());
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            try {
                DatePIcker.setDate(dateFormat.parse(tv.getNgaysinh()));
            } catch (ParseException ex) {
                Logger.getLogger(GDQLThanhvien.class.getName()).log(Level.SEVERE, null, ex);
            }
            MAHGDTF.setText(tv.getMahgd());
            SOCMNDTF.setText(tv.getSocmnd());
            EMAILTF.setText(tv.getEmail());
            if(tv.getGioitinh().equals("NAM"))
                NAMCHECK.setSelected(true);
             if(tv.getGioitinh().equals("NỮ"))
                NUCHECK.setSelected(true);
            btnOK.setEnabled(true);
            btnThem.setEnabled(false);
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
        }
    }//GEN-LAST:event_TBThanhvienMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DatePIcker;
    private javax.swing.JTextField EMAILTF;
    private javax.swing.JTextField HOTENTF;
    private javax.swing.JTextField MAHGDTF;
    private javax.swing.JComboBox<String> MATVCB;
    private javax.swing.JTextField MATVTF;
    private javax.swing.JRadioButton NAMCHECK;
    private javax.swing.JRadioButton NUCHECK;
    private javax.swing.JTextField SDTTF;
    private javax.swing.JTextField SOCMNDTF;
    private javax.swing.JTable TBThanhvien;
    private javax.swing.JTable TVTBALE;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
