/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import Entity.HGDObject;
import Entity.HoadonObject;
import Entity.NhanvienObject;
import NguoidungUse.HGDsevice;
import NguoidungUse.HoadonUse;
import NguoidungUse.NhanvienUse;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.BufferOverflowException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFChartSheet;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Admin
 */
public class GDXEMHOADON extends javax.swing.JPanel {
    DefaultTableModel defaultTableModel ;
    HoadonUse hoadonUse;
    NhanvienUse nhanvienUse = new NhanvienUse();
    HGDsevice hgd = new HGDsevice();
    /**
     * Creates new form GDXEMHOADON
     */
    public GDXEMHOADON() {
        hoadonUse = new HoadonUse();
        initComponents();
//        Load_manv();
//        Load_mahgd();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        defaultTableModel.addColumn("Mã hóa đơn");
        defaultTableModel.addColumn("Mã hộ gia đình");
        defaultTableModel.addColumn("Mã căn hộ");
        defaultTableModel.addColumn("Tiền điện");
        defaultTableModel.addColumn("Tiền nước");
        defaultTableModel.addColumn("Tiền dịch vụ");
        defaultTableModel.addColumn("Ngày");
        defaultTableModel.addColumn("Mã nhân viên");
        defaultTableModel.addColumn("Tổng tiền");
        
        TBHoadon.setModel(defaultTableModel);
        defaultTableModel.setRowCount(0);
        setData(hoadonUse.getALL());
        
        loadTK(hoadonUse.getALL());
    }

    public void loadTK( List<HoadonObject> list)
    {
        NumberFormat numberFormatter = new DecimalFormat("#,###,###");
        float sum1 = 0;
        for (HoadonObject hd : list) {
            sum1 +=hd.getTiendien();
        }
        DienTf.setText(String.valueOf(numberFormatter.format(sum1)));
        float sum2 = 0;
        for (HoadonObject hd : list) {
            sum2 +=hd.getTiendv();
        }
        DvTF.setText(String.valueOf(numberFormatter.format(sum2)));
        float sum3 = 0;
        for (HoadonObject hd : list) {
            sum3 +=hd.getTiennuoc();
        }
        NuocTF.setText(String.valueOf(numberFormatter.format(sum3)));
        
        float tong = 0;
        tong = sum1 + sum2 + sum3;
        TongTF.setText(String.valueOf(numberFormatter.format(tong)));
    }
    public void setData(List<HoadonObject> list)
    {
        NumberFormat numberFormatter = new DecimalFormat("#,###,###");
        for (HoadonObject hd : list) {
            defaultTableModel.addRow(new Object[]{
                hd.getMahd(),hd.getMahgd(),hd.getMach(),
                numberFormatter.format(hd.getTiendien()),
                numberFormatter.format(hd.getTiennuoc()),numberFormatter.format(hd.getTiendv()),
                hd.getNgay(),hd.getManv(),numberFormatter.format(hd.getTongtien())
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnXem = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBHoadon = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DvTF = new javax.swing.JTextField();
        DienTf = new javax.swing.JTextField();
        TongTF = new javax.swing.JTextField();
        NuocTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbghichu = new javax.swing.JLabel();
        SpThang = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        SpNam = new javax.swing.JSpinner();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("THÔNG TIN THỐNG KÊ HÓA ĐƠN");

        jLabel2.setText("Tháng");

        btnXem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/look.png"))); // NOI18N
        btnXem.setText("Xem");
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });

        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/printing.png"))); // NOI18N
        btnIn.setText("In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 51, 255))); // NOI18N

        TBHoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBHoadon);

        jLabel3.setText("Dịch vụ");

        jLabel5.setText("Nước");

        jLabel6.setText("Điện");

        jLabel7.setText("Tổng");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Thông kê");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(DvTF, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addComponent(NuocTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addComponent(DienTf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(TongTF))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel8)
                .addGap(607, 607, 607)
                .addComponent(jLabel7)
                .addContainerGap(310, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(DvTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DienTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TongTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NuocTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 141, Short.MAX_VALUE)))
        );

        lbghichu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbghichu.setText("Ghi chú");

        SpThang.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpThangStateChanged(evt);
            }
        });

        jLabel4.setText("Năm");

        SpNam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                SpNamPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(SpThang, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(SpNam, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnXem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(365, 365, 365)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(lbghichu)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SpThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(SpNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbghichu)
                .addGap(62, 62, 62))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed
        // TODO add your handling code here:
        int month = Integer.valueOf(String.valueOf(SpThang.getValue()));
        int year = Integer.valueOf(String.valueOf(SpNam.getValue()));
        
        List<HoadonObject> list1 = hoadonUse.GetWMonth(month);
        List<HoadonObject> list2 = hoadonUse.GetWYear(year);
        if(month > 0)
        {
            defaultTableModel.setRowCount(0);
            setData(list1);
            loadTK(list1);
        }
        if(year > 0)
        {
            defaultTableModel.setRowCount(0);
            setData(list2);
            loadTK(list2);
        }
    }//GEN-LAST:event_btnXemActionPerformed

    private void SpThangStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpThangStateChanged
        // TODO add your handling code here:
        int month = Integer.valueOf(String.valueOf(SpThang.getValue()));
        if(month  > 0)
            SpNam.setEnabled(false);
    }//GEN-LAST:event_SpThangStateChanged

    private void SpNamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_SpNamPropertyChange
        // TODO add your handling code here:
        int year = Integer.valueOf(String.valueOf(SpNam.getValue()));
        if(year  > 0)
            SpThang.setEnabled(false);
    }//GEN-LAST:event_SpNamPropertyChange

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("C:\\Users\\Admin\\Documents\\JavaSwingfile");
        fileChooser.setDialogTitle("Save as");
        // chọn định dạng files excel
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("FILE EXCELS", "xlsx","xls");
        fileChooser.setFileFilter(extensionFilter);
        int extenchooser = fileChooser.showSaveDialog(null);
        FileOutputStream fileOutputStream = null;
        BufferedOutputStream bos = null;
        XSSFWorkbook excelJtable = null;
        if(extenchooser == JFileChooser.APPROVE_OPTION)
        {
            
            try {
                 // import excel poi libraries to netbeans
                excelJtable = new XSSFWorkbook();
                XSSFSheet fSheet = excelJtable.createSheet("HÓA ĐƠN");
                for (int i = 0; i < TBHoadon.getRowCount(); i++) {
                    XSSFRow fRow = fSheet.createRow(i);
                    
                    for (int j = 0; j < TBHoadon.getColumnCount(); j++) {
                        XSSFCell cell = fRow.createCell(j);
                        
                        cell.setCellValue(TBHoadon.getValueAt(i, j).toString());
                    }
                }
                // mở file kiểu nguyên thủy này giúp mở file có kí tự
                fileOutputStream = new FileOutputStream(fileChooser.getSelectedFile() + ".xlsx");
                 // dùng bộ nhớ điệm để lưu dữ liệu giúp cho việc xuất dữ liệu ko thông qua luồng trực tiếp mà thông qua luồng đệm nên lấy dự liệu nhanh hơn
                bos = new BufferedOutputStream(fileOutputStream);
                try {
                    excelJtable.write(bos);
                } catch (IOException ex) {
                    Logger.getLogger(GDXEMHOADON.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "XUẤT FILE EXCEL THÀNH CÔNG");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GDXEMHOADON.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
                try {
                    if(bos !=null)
                        bos.close();
                    if(fileOutputStream !=null)
                        fileOutputStream.close();
                    if(excelJtable !=null)
                        excelJtable.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DienTf;
    private javax.swing.JTextField DvTF;
    private javax.swing.JTextField NuocTF;
    private javax.swing.JSpinner SpNam;
    private javax.swing.JSpinner SpThang;
    private javax.swing.JTable TBHoadon;
    private javax.swing.JTextField TongTF;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnXem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbghichu;
    // End of variables declaration//GEN-END:variables
}
