/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import Dao.CanhoDao;
import Entity.HGDObject;
import Entity.canhoOject;
import NguoidungUse.CanhoSevice;
import NguoidungUse.HGDsevice;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class GGCanho extends javax.swing.JPanel {
    DefaultTableModel defaultTableModel ;
    CanhoSevice canhoSevice;
    canhoOject canho ;
    HGDsevice hgd = new HGDsevice();
    /**
     * Creates new form 
     */
    public GGCanho() {
        canho = new canhoOject();
        canhoSevice = new CanhoSevice();
        initComponents();
        BTNTHEM.setEnabled(false);
        loadMAHGD();
            defaultTableModel = new DefaultTableModel(){
                @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
        CHTABLE.setModel(defaultTableModel);
        defaultTableModel.addColumn("MÃ CĂN HỘ ");
        defaultTableModel.addColumn("MÃ KHU ");
        defaultTableModel.addColumn("LOẠI CĂN HỘ");
        defaultTableModel.addColumn("MÃ LOẠI CĂN HỘ");
        defaultTableModel.addColumn("GHI CHÚ ");
        defaultTableModel.addColumn("GIÁ ");
        defaultTableModel.addColumn("TRẠNG THÁI ");
        
        setData(canhoSevice.getALLCH());
    }
//    public void LoadMaKhu()
//    {
//        Dao.CanhoDao ch = new CanhoDao();
//        List<canhoOject> list = ch.getListKhu();
//        MAKHU.removeAllItems();
//        for (canhoOject canho : list) {
//             MAKHU.addItem(canho.getMa_khu());
//        }
//    }
    public void loadMAHGD()
    {
        Dao.CanhoDao ch = new CanhoDao();
        List<canhoOject> list = ch.GetListML();
        MAHOGD.removeAllItems();
        for (canhoOject hGDObject : list) {
             MAHOGD.addItem(hGDObject.getMa_loai_can_ho());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MACH = new javax.swing.JTextField();
        GIA = new javax.swing.JTextField();
        GHICHU = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MAHOGD = new javax.swing.JComboBox<>();
        LOAICANHO = new javax.swing.JComboBox<>();
        MAKHU = new javax.swing.JComboBox<>();
        TRANGTHAI = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CHTABLE = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        BTNXOA = new javax.swing.JButton();
        BTNTHEM = new javax.swing.JButton();
        BTNSUA = new javax.swing.JButton();
        BTNTIMKIEM = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        BTNDONG = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(900, 580));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMaximumSize(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÝ CĂN HỘ");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin căn hộ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel2.setText("Mã căn hộ");

        jLabel3.setText("Giá");

        jLabel4.setText("Ghi chú");

        MACH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MACHKeyPressed(evt);
            }
        });

        jLabel5.setText("Mã khu");

        jLabel6.setText("Mã loại căn hộ");

        jLabel7.setText("Loại căn hộ");

        jLabel8.setText("Trạng thái");

        LOAICANHO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thông thường", "Sky Pilla", "Cao cấp" }));

        MAKHU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "K01", "K02", "K03", "K04" }));

        TRANGTHAI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã thuê", "Chưa thuê", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MACH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(GIA, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addGap(1, 1, 1))
                        .addComponent(GHICHU)))
                .addGap(177, 177, 177)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MAKHU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MAHOGD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LOAICANHO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TRANGTHAI, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(MAKHU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(MAHOGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(LOAICANHO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TRANGTHAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(MACH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GIA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(GHICHU, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách căn hộ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 51, 255))); // NOI18N

        CHTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CHTABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CHTABLEMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CHTABLE);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        BTNXOA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Delete.png"))); // NOI18N
        BTNXOA.setText("Xóa");
        BTNXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNXOAActionPerformed(evt);
            }
        });

        BTNTHEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Add.png"))); // NOI18N
        BTNTHEM.setText("Thêm");
        BTNTHEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTHEMActionPerformed(evt);
            }
        });

        BTNSUA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Edit.png"))); // NOI18N
        BTNSUA.setText("Sửa");
        BTNSUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSUAActionPerformed(evt);
            }
        });

        BTNTIMKIEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/search-icon-24.png"))); // NOI18N
        BTNTIMKIEM.setText("Tìm kiếm");
        BTNTIMKIEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTIMKIEMActionPerformed(evt);
            }
        });

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/reuse.png"))); // NOI18N
        btnOk.setText("Làm mới");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        BTNDONG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Button-Close-icon-16.png"))); // NOI18N
        BTNDONG.setText("Đóng");
        BTNDONG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDONGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNTHEM)
                .addGap(50, 50, 50)
                .addComponent(BTNSUA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BTNXOA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(BTNTIMKIEM)
                .addGap(50, 50, 50)
                .addComponent(BTNDONG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNTIMKIEM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNXOA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNSUA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNTHEM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNDONG, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNTHEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTHEMActionPerformed
        // TODO add your handling code here:
        canhoOject ch = new canhoOject();
        ch.setMa_can_ho(MACH.getText());
        String loaiCH = String.valueOf(LOAICANHO.getSelectedItem());
        ch.setLoai_can_ho(loaiCH);
        String makhu = String.valueOf(MAKHU.getSelectedItem());
        ch.setMa_khu(makhu);
        String trangthai = String.valueOf(TRANGTHAI.getSelectedItem());
        ch.setTrang_thai(trangthai);
        String mahgd = String.valueOf(MAHOGD.getSelectedItem());
        ch.setMa_loai_can_ho(mahgd);
        ch.setGhi_chu(GHICHU.getText());
        ch.setGia(Float.valueOf(GIA.getText()));
        
        if(canhoSevice.CheckADD(MACH.getText()) == 1)
        {
            JOptionPane.showMessageDialog(this, "Mã căn hộ '"+MACH.getText()+"' đã tồn tại","Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Thêm thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
            canhoSevice.themCH(ch);
            defaultTableModel.setRowCount(0);
            setData(canhoSevice.getALLCH());
            ClearText();
        }
    }//GEN-LAST:event_BTNTHEMActionPerformed

    private void BTNSUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSUAActionPerformed
        // TODO add your handling code here:
        canho.setMa_can_ho(MACH.getText());
        canho.setGia(Float.valueOf(GIA.getText()));
        canho.setGhi_chu(GHICHU.getText());
        canho.setMa_khu(String.valueOf(MAKHU.getSelectedItem()));
        canho.setLoai_can_ho(String.valueOf(LOAICANHO.getSelectedItem()));
        canho.setMa_loai_can_ho(String.valueOf(MAHOGD.getSelectedItem()));
        canho.setTrang_thai(String.valueOf(TRANGTHAI.getSelectedItem()));
        
        canhoSevice.updateCH(canho);
        defaultTableModel.setRowCount(0);
        setData(canhoSevice.getALLCH());
        ClearText();
    }//GEN-LAST:event_BTNSUAActionPerformed

    private void BTNXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNXOAActionPerformed
        // TODO add your handling code here:
        int row = CHTABLE.getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(this, "HÃY CHỌN DÒNG CẦN XÓA ", "LỖI", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String mach = String.valueOf(CHTABLE.getValueAt(row, 0));
            int comfirm  = JOptionPane.showConfirmDialog(this, "BẠN CÓ CHẮC CHẮN MUỐN XÓA KHÔNG ?");
            if(comfirm == JOptionPane.YES_OPTION)
            {
                canhoSevice.xoaCH(mach);
                defaultTableModel.setRowCount(0);
                setData(canhoSevice.getALLCH());
                ClearText();
            }
        }
    }//GEN-LAST:event_BTNXOAActionPerformed

    private void BTNTIMKIEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTIMKIEMActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("NHẬP MÃ CĂN HỘ CẦN TÌM :");
        canho = canhoSevice.getONE(input);
        defaultTableModel.setRowCount(0);
        defaultTableModel.addRow( new Object[] {canho.getMa_can_ho(),canho.getMa_khu(),canho.getLoai_can_ho(),canho.getMa_loai_can_ho(),canho.getGhi_chu(),canho.getGia(),canho.getTrang_thai()});
        
    }//GEN-LAST:event_BTNTIMKIEMActionPerformed

    private void BTNDONGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDONGActionPerformed
        // TODO add your handling code here:
        int comfirm = JOptionPane.showConfirmDialog(this, "BẠN CÓ CHẮC CHẮN MUỐN THOÁT KHÔNG ?");
        if(comfirm == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_BTNDONGActionPerformed
    void ClearText()
    {
        MACH.setText("");
        GIA.setText("");
        GHICHU.setText("");
        MAKHU.setSelectedIndex(0);
        MAHOGD.setSelectedIndex(0);
        LOAICANHO.setSelectedIndex(0);
        TRANGTHAI.setSelectedIndex(0);
    }
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        ClearText();
        btnOk.setEnabled(true);
        BTNTHEM.setEnabled(true);
        BTNSUA.setEnabled(false);
        BTNXOA.setEnabled(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void CHTABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHTABLEMouseClicked
        // TODO add your handling code here:
        int row = CHTABLE.getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(this, "HÃY CHỌN DÒNG CẦN SỬA ", "LỖI", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String maCH = String.valueOf(CHTABLE.getValueAt(row, 0));
            canho = canhoSevice.getONE(maCH);
            MACH.setText(canho.getMa_can_ho());
            GIA.setText(String.valueOf(Float.valueOf(canho.getGia())));
            GHICHU.setText(canho.getGhi_chu());
            String makhu = String.valueOf(canho.getMa_khu());
            String trangthai = String.valueOf(canho.getTrang_thai());
            String mahgd = String.valueOf(canho.getMa_loai_can_ho());
            String loaicanho = String.valueOf(canho.getLoai_can_ho());
            MAKHU.setSelectedItem(makhu);
            MAHOGD.setSelectedItem(mahgd);
            LOAICANHO.setSelectedItem(loaicanho);
            TRANGTHAI.setSelectedItem(trangthai);
            btnOk.setEnabled(true);
            BTNTHEM.setEnabled(false);
            BTNSUA.setEnabled(true);
            BTNXOA.setEnabled(true);
        }
    }//GEN-LAST:event_CHTABLEMouseClicked

    private void MACHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MACHKeyPressed
        // TODO add your handling code here:
        if(MACH.getText().equals(""))
            BTNTHEM.setEnabled(false);
        else
            BTNTHEM.setEnabled(true);
    }//GEN-LAST:event_MACHKeyPressed

    public void setData(List<canhoOject> list)
    {
        for (canhoOject ch : list) {
            defaultTableModel.addRow( new Object[] {ch.getMa_can_ho(),ch.getMa_khu(),ch.getLoai_can_ho(),ch.getMa_loai_can_ho(),ch.getGhi_chu(),ch.getGia(),ch.getTrang_thai()});
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNDONG;
    private javax.swing.JButton BTNSUA;
    private javax.swing.JButton BTNTHEM;
    private javax.swing.JButton BTNTIMKIEM;
    private javax.swing.JButton BTNXOA;
    private javax.swing.JTable CHTABLE;
    private javax.swing.JTextField GHICHU;
    private javax.swing.JTextField GIA;
    private javax.swing.JComboBox<String> LOAICANHO;
    private javax.swing.JTextField MACH;
    private javax.swing.JComboBox<String> MAHOGD;
    private javax.swing.JComboBox<String> MAKHU;
    private javax.swing.JComboBox<String> TRANGTHAI;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
